config/routes.rb
InventoryTest::Application.routes.draw do
  resources :entries
  resources :employees
  root 'entries#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :email

  validates_uniqueness_of :email

  validates_format_of :email, :with => VALID_EMAIL_REGEX, :on => :create 

  has_many :entries 



end

app/models/entry.rb
class Entry < ActiveRecord::Base

  validates_presence_of :title
  validates_presence_of :employee_id
  validates_presence_of :quantity

  belongs_to :employee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to root_path, notice: 'Employee Created Successfully'
    else
      render 'new'
    end
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:first_name,:last_name,:email)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def new
    @entry = Entry.new
  end

  def index
    @entries = Entry.all
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      redirect_to root_path, notice: 'Entry Created Successfully'
    else
      render 'new'
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:title,:description,:quantity,:employee_id)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/employees/new.html.erb
<h1> New Employee </h1>

<%= simple_form_for @employee  do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :email %>
  <%= f.submit %>
<% end %>

app/views/entries/index.html.erb
<h1> List of Entries </h1>
<%= @entries.each do |entry| %>
  <div><%= "#{entry.title}: #{entry.quantity}. #{entry.employee.first_name} #{entry.employee.last_name}" %></div>
<% end %>


<p><%= link_to 'Add Entry', new_entry_path %></p>
<p><%= link_to 'Add Employee', new_employee_path %></p>

app/views/entries/new.html.erb
<h1> New Entry </h1>

<%= simple_form_for @entry do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :quantity %>
  <%= f.association :employee,:collection => Employee.all,:label_method => :email,:value_method => :id %>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InventoryTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p id="notice"><%= notice %></p>

<%= yield %>

</body>
</html>